apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-modifier-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-modifier
  apiGroup: rbac.authorization.k8s.io
