apiVersion: v1
kind: Pod
metadata:
  name: tomcat-detector
  namespace: default
spec:
  serviceAccountName: internal-kubectl
  containers:
    - name: tomcat-detector
      image: tomcat_detector:alpha
      imagePullPolicy: IfNotPresent
      tty: true
      volumeMounts:
      - name: httpd-configuration
        mountPath: /httpd_configuration.py
        subPath: httpd_configuration.py
  volumes:
  - name: httpd-configuration
    configMap:
      name: tomcat-detector-configmap