apiVersion: v1
kind: Pod
metadata:
  name: tomcat-detector
  namespace: default
spec:
  serviceAccountName: internal-kubectl
  containers:
    - name: tomcat-detector
      image: tomcat_detector:beta
      imagePullPolicy: IfNotPresent
      tty: true
      volumeMounts:
      - name: configuration
        mountPath: /tomcat-detector/config.yml
        subPath: config.yml
  volumes:
  - name: configuration
    configMap:
      name: tomcat-detector-configmap